-- Ventilator-Kalkulation (Zuschlagskalkulation, Excel V11.0)
-- + material_presets bekommt calc_type (schallkabine / ventilator)

ALTER TABLE material_presets ADD COLUMN calc_type TEXT NOT NULL DEFAULT 'schallkabine';

-- Arbeitsgänge Ventilator (stundenbasiert, Stundensätze aus Excel V11.0)
INSERT INTO step_templates (calc_type, pos, name, rate, setup_min) VALUES
  ('ventilator', 1, 'Büro / Konstruktion', 60, 0),
  ('ventilator', 2, 'Laserzeit komplett', 75, 0),
  ('ventilator', 3, 'Entgraten / Schleifen komplett', 75, 0),
  ('ventilator', 4, 'Biegezeit komplett', 70, 0),
  ('ventilator', 5, 'Rundeln Gehäuse', 55, 0),
  ('ventilator', 6, 'Heften Gehäuse', 60, 0),
  ('ventilator', 7, 'Schweißen Gehäuse', 60, 0),
  ('ventilator', 8, 'Verputzen Gehäuse', 60, 0),
  ('ventilator', 9, 'Heften Bock', 60, 0),
  ('ventilator', 10, 'Schweißen Bock', 60, 0),
  ('ventilator', 11, 'Verputzen Bock', 60, 0),
  ('ventilator', 12, 'Zusägen Grundrahmen', 60, 0),
  ('ventilator', 13, 'Bohren Grundrahmen', 60, 0),
  ('ventilator', 14, 'Heften Grundrahmen', 60, 0),
  ('ventilator', 15, 'Schweißen Grundrahmen', 60, 0),
  ('ventilator', 16, 'Verputzen Grundrahmen', 60, 0),
  ('ventilator', 17, 'Überfräsen Bock', 65, 0),
  ('ventilator', 18, 'Überfräsen Motorplatte', 65, 0),
  ('ventilator', 19, 'Drehen Nabe', 65, 0),
  ('ventilator', 20, 'Nabe Schweißen', 65, 0),
  ('ventilator', 21, 'Nabe Nuten', 65, 0),
  ('ventilator', 22, 'Sonstiges Mechanik', 58, 0),
  ('ventilator', 23, 'Rundeln Düse', 55, 0),
  ('ventilator', 24, 'Drücken Düse', 200, 0),
  ('ventilator', 25, 'Heften Düse', 58, 0),
  ('ventilator', 26, 'Schweißen Düse', 58, 0),
  ('ventilator', 27, 'Verputzen Düse', 58, 0),
  ('ventilator', 28, 'Schaufeln Rundeln Laufrad', 55, 0),
  ('ventilator', 29, 'Drückteil Laufrad', 200, 0),
  ('ventilator', 30, 'Heften Laufrad', 69, 0),
  ('ventilator', 31, 'Schweißen Laufrad', 69, 0),
  ('ventilator', 32, 'Verputzen Laufrad', 69, 0),
  ('ventilator', 33, 'Wuchten Laufrad', 70, 0),
  ('ventilator', 34, 'Schweißen Flansche', 58, 0),
  ('ventilator', 35, 'Schweißen Rahmen', 58, 0),
  ('ventilator', 36, 'Schweißen Stützhülse', 58, 0),
  ('ventilator', 37, 'Schweißen Riemenschutz', 58, 0),
  ('ventilator', 38, 'Schweißen Sonstiges 1', 58, 0),
  ('ventilator', 39, 'Schweißen Sonstiges 2', 58, 0),
  ('ventilator', 40, 'Schweißen Kulissenschalldämpfer', 58, 0),
  ('ventilator', 41, 'Lackierung incl. waschen komplett', 72, 0),
  ('ventilator', 42, 'Montage Blocklager/Stehlager', 63, 0),
  ('ventilator', 43, 'Montage Werk 1', 63, 0),
  ('ventilator', 44, 'Isolierung mit Vorbereitung', 63, 0),
  ('ventilator', 45, 'VT Prüfung / PT Prüfung', 70, 0),
  ('ventilator', 46, 'Probelauf/Abnahme/Doku', 70, 0),
  ('ventilator', 47, 'Allgemeines Handling', 58, 0),
  ('ventilator', 48, 'Verpackung / Versand', 58, 0),
  ('ventilator', 49, 'Sonstiges', 58, 0);

-- Material-Vorlagen Ventilator (Bauteile + Zukauf/Isolierung, Excel V11.0)
INSERT INTO material_presets (calc_type, pos, name, comment, supplier, unit_price) VALUES
  ('ventilator', 1, 'Gehäuse', '', '1.0038', 0),
  ('ventilator', 2, 'Bock', '', '1.4301', 0),
  ('ventilator', 3, 'Grundrahmen', '', '1.4462', 0),
  ('ventilator', 4, 'Düsenwanne', '', '1.4541', 0),
  ('ventilator', 5, 'Distanzstrebe', '', '1.4541', 0),
  ('ventilator', 6, 'Träger', '', '1.0038', 0),
  ('ventilator', 7, 'Tragwanne', '', '1.4301', 0),
  ('ventilator', 8, 'Laufrad Rückwand', '', '1.0570', 0),
  ('ventilator', 9, 'Laufrad Zwischenring', '', '1.0570', 0),
  ('ventilator', 10, 'Laufrad Konus + Knotenbleche', '', '1.0570', 0),
  ('ventilator', 11, 'Laufrad Deckscheibe', '', '1.0570', 0),
  ('ventilator', 12, 'Laufrad Schaufeln', '', '1.8928', 0),
  ('ventilator', 13, 'Saugdeckel / Düse', '', '1.0038', 0),
  ('ventilator', 14, 'Kulissenschalldämpfer Gehäuse', '', '1.0038', 0),
  ('ventilator', 15, 'Leitblech mit 2x Flansch ansaug', '', '1.0038', 0),
  ('ventilator', 16, 'Leitblech mit 2x Flansch ausblas', '', '1.0038', 0),
  ('ventilator', 17, 'Schutzhaube (Schutzgitter)', '', '1.0038', 0),
  ('ventilator', 18, 'Wellenschutz', '', '1.0038', 0),
  ('ventilator', 19, 'Kupplungsschutz', '', '1.0038', 0),
  ('ventilator', 20, 'Kulisse lang', '', 'verzinkt 1mm', 0),
  ('ventilator', 21, 'Kulisse kurz', '', 'verzinkt 1mm', 0),
  ('ventilator', 22, 'Streckmetall', '', '1.0038', 0),
  ('ventilator', 23, 'Wellengitter', '14€/Stück', '1.0038', 14),
  ('ventilator', 24, 'Isolierungsmaterial Blech', '', 'verzinkt 1mm', 0),
  ('ventilator', 25, 'Verschraubungsmaterial', '', 'Würth', 0),
  ('ventilator', 26, 'Nabe', '', 'Divers', 0),
  ('ventilator', 27, 'Welle', '', 'Ehlert', 0),
  ('ventilator', 28, 'Fett für Lager', '', 'Divers', 0),
  ('ventilator', 29, 'Isolierungs-Matte bis 80°C (40-200mm)', 'in m² 100mm', 'Sonorock 100', 9.1),
  ('ventilator', 30, 'Isolierungs-Matte bis 80°C (40-200mm)', 'in m² 50mm', 'Sonorock 50', 4.66),
  ('ventilator', 31, 'Isolierungs-Platte bis 660°C (30-100mm)', 'in m² 50mm', 'Knauf Power teK', 10.31),
  ('ventilator', 32, 'Isolierungs-Matte bis 1100°C (6-50mm)', 'in m² 50mm', 'Insulfrax LTX', 28.28),
  ('ventilator', 33, 'Isolierungsmaterial-Hitzefest', 'in m² 100mm', 'Promat weiß', 25),
  ('ventilator', 34, 'Isolierungsmaterial Platte', 'Je Platte 1000x1000', 'Isoplan 850°', 45),
  ('ventilator', 35, 'Glühen', '65€ Grundkosten', 'Raiser', 65),
  ('ventilator', 36, 'Sandstrahlen / Glasperlenstrahlen', '1€/Kg', 'Raiser/Pfeiffer', 1),
  ('ventilator', 37, 'Überfräsen Lagerböcke', '', 'Raiser', 0),
  ('ventilator', 38, 'Pulverbeschichten', '1€/Kg', '', 1),
  ('ventilator', 39, 'Beizen', '1€/Kg', 'Inox', 1),
  ('ventilator', 40, 'Materialeinkauf (Pneumatik/Hahnen/Nutmutter…)', '', 'Divers', 0),
  ('ventilator', 41, 'Einkauf Brennzuschnitte', '2€/Kg rechnen', '', 2),
  ('ventilator', 42, 'Fahrtkosten', 'siehe Versandkostenliste', '', 0);
